### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by ealpha072** [EvansRobbie/Resume-Builder#3]
Is this open source ? If so are there any collaboration documentation
Also, i realized that the node_modules folder has been pushed which makes it take a longer time to clone.

**Comment by EvansRobbie** [comment]
Initially it was a personal project,but yes it's an open source project and no I don't have any collaboration documentation at the moment. Feel free to open a PR on the issue..

**Comment by ealpha072** [comment]
Could you uncommit the node_modules folder in the api directory ?😅, it'll be easier to fork and clone

**Comment by EvansRobbie** [comment]
Let me add a good first issue label but i'll look into it by the end of the week.

**Comment by ealpha072** [comment]
Amazing, let me know when you do

**Comment by EvansRobbie** [comment]
Hello @ealpha072, 
This issue is now resolved.

**Comment by EvansRobbie** [comment]
Done
